vich_uploader:
    db_driver: orm

    mappings:
       mission_justification:
           uri_prefix: /justifications
           upload_destination: '%kernel.project_dir%/public/uploads/justifications'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
